### ISSUE TITLE
Wrong installation prefix with cmake3 on CentOS 7.6

### ISSUE THREAD

**Issue by sviscapi** [irods/irods_resource_plugin_rados#15]
Hi,

I had a similar issue to this already closed one:

https://github.com/irods/irods_resource_plugin_rados/issues/5

Cmake3 installation prefix is still /usr/local on CentOS 7.6, installing the RADOS plugin to the wrong place (i.e /usr/local/usr/lib...). It's no big deal though, I just removed that prefix and re-compiled the plugin.

Could you please have a look ?

Cheers, Samuel from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by sviscapi** [comment]
Hi again,

Some more details after a simple "cmake3 .." from the build directory:

`[viscapi@sandbox10 build]$ grep -ri /usr/local *
CMakeCache.txt:CMAKE_INSTALL_PREFIX:PATH=/usr/local
cmake_install.cmake:  set(CMAKE_INSTALL_PREFIX "/usr/local")
CPackConfig.cmake:set(CPACK_INSTALL_PREFIX "/usr/local")
CPackSourceConfig.cmake:set(CPACK_INSTALL_PREFIX "/usr/local")`

Even though the CPACK_PACKAGING_INSTALL_PREFIX is set to '/':

`-- Setting unspecified CPACK_PACKAGING_INSTALL_PREFIX to '/'. This is the correct setting for normal builds.`

Cheers, Samuel from CINES (Montpellier, France)

https://www.cines.fr/en/

**Comment by trel** [comment]
I've built master just now on CentOS7 via `make package` and see the following files in the .rpm:
```
$ rpm -qlp irods-resource-plugin-rados-4.2.4-centos7-x86_64.rpm 
/usr/lib/irods
/usr/lib/irods/plugins
/usr/lib/irods/plugins/resources
/usr/lib/irods/plugins/resources/libirados.so
```

Can you share the series of commands you're using?

**Comment by sviscapi** [comment]
Hi Terrell,

You are right, I didn't run the "make package" command, only "make ; make install" as per the documentation. 

Sorry for the noise :)

Cheers, Samuel
