### ISSUE TITLE
undefined symbols

### ISSUE THREAD

**Issue by robnaccy** [irods/irods_resource_plugin_rados#4]
Went to try this out in our 4.2.1 iRODS environment and am getting the following in the irods log

```
Aug 15 16:44:50 pid:114854 remote addresses: 10.20.29.101, 10.20.29.102 ERROR: [-]	/home/irodsbuild/irods/server/core/src/irods_resource_manager.cpp:669:irods::error irods::resource_manager::process_init_results(genQueryOut_t *) :  status [PLUGIN_ERROR]  errno [] -- message []
	[-]	/home/irodsbuild/irods/server/core/src/irods_resource_manager.cpp:122:irods::error irods::resource_manager::load_resource_plugin(resource_ptr &, const std::string, const std::string, const std::string) :  status [PLUGIN_ERROR]  errno [] -- message []
		[-]	/home/irodsbuild/irods/lib/core/include/irods_load_plugin.hpp:176:irods::error irods::load_plugin(PluginType *&, const std::string &, const std::string &, const std::string &, const std::string &) [PluginType = irods::resource] :  status [PLUGIN_ERROR]  errno [] -- message [failed to open shared object file [/usr/lib/irods/plugins/resources/libirados.so] :: dlerror: is [/usr/lib/irods/plugins/resources/libirados.so: undefined symbol: _ZN5irods8resource9add_childERKSsS2_N5boost10shared_ptrIS0_EE]]
```
The machine is Ubuntu 14.04 with packages from 4.2.1 of iRODS and 10.2.9 of Ceph.

The irados/Makefile needed to be changed, since the static `libirods_client.a` file doesn't exist.

``` Makefile
#EXTRALIBS = /usr/lib/irods/libirods_client.a -lrados 
EXTRALIBS = -lirods_client  -lrados
```

Also had to add `-std=gnu++11` to GCC in order to allow compilation, due to warning from `/usr/include/c++/4.8/bits/c++0x_warning.h` about ISO C++ 2011 standards.

Copying the resulting `libirados.so` to `/usr/lib/irods/plugins/resources/libirados.so` is fine, but when restarting the irods server or attempting to `iput` to the resource fails with the above log entry.

**Comment by trel** [comment]
Hi @robnaccy - we're actively preparing this codebase for compatibility with iRODS 4.2+.  There were a great number of things that moved in the overhaul of our buildchain with 4.2.

**Comment by trel** [comment]
I think this is resolved - can you confirm?

**Comment by trel** [comment]
closing for now - please open if new issues are found.
