### ISSUE TITLE
Plugin installed to wrong location

### ISSUE THREAD

**Issue by kwaegema** [irods/irods_resource_plugin_rados#5]
I installed the plugin and set up the resources as in the readme on a resource server, but when I try to put a file in, I get:
```
remote addresses: 157.193.231.206 ERROR: putUtil: put error for /ZONE/home/kwaegema/myfile3, status = -1818000 status = -1818000 INVALID_ACCESS_TO_IMPOSTOR_RESOURCE
```
On the resource server, I see this is the log
```
Nov 22 15:25:04 pid:46364 NOTICE: rodsServer Release version rods4.2.1 - API Version d is up
Nov 22 15:25:04 pid:46364 NOTICE: >>> control plane :: listening on port 1248
Nov 22 15:25:20 pid:46418 remote addresses: 157.193.231.206 ERROR: [-]  /home/irodsbuild/irods/server/api/src/rsFileCreate.cpp:220:int _rsFileCreate(rsComm_t *, fileCreateInp_t *, rodsServerHost_t *, fileCreateOut_t **) :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [UNHANDLED fileCreate for [//home/kwaegema/myfile3]]
        [-]     /home/irodsbuild/irods/server/drivers/src/fileDriver.cpp:38:irods::error fileCreate(rsComm_t *, irods::first_class_object_ptr) :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [failed to call 'create']
                [-]     /home/irodsbuild/irods/server/core/src/irods_resource_plugin_impostor.cpp:555:static irods::error irods::impostor_resource::report_error(irods::plugin_context &) :  status [INVALID_ACCESS_TO_IMPOSTOR_RESOURCE]  errno [] -- message [NOTE :: Direct Access of Impostor Resource [radosResc1] of Given Type [irados]]
```

How can I debug more what is going on here?

Thanks!

**Comment by trel** [comment]
The impostor resource error means that you need to install the rados plugin on that server as well.  Can you successfully put a file when only the server holding the rados resource is involved in the connection?

**Comment by kwaegema** [comment]
Hi, 
I installed it on the icat server as well, that didnt solve it. But I saw that the 'make install' did install the plugin in another location than it should be. I copied the .so file to the correct location and now it works 😄 
`` cp /usr/local/usr/lib/irods/plugins/resources/libirados.so /usr/lib/irods/plugins/resources/``
Thanks!!

**Comment by trel** [comment]
Ah, that would definitely do it.

If you can capture the steps you took, we can reproduce it.   Or if you can find the error yourself, please send a pull request - sounds like a simple fix.

Thanks!
